---
- name: AWS Provision
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  vars:
    favcolor: blue
  vars_files:
    - credentials.yml
    - ./group_vars/tasks/main.yml

  roles:
    - cria_vpc
    - cria_subnets
    - cria_sg
    - cria_igw
    - cria_rt
    - cria_ec2


