- name: Criando VPC
  amazon.aws.ec2_vpc_net:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    state: present
    region: "{{ aws_vars.aws.common.region }}"
    cidr_block: "{{ aws_vars.aws.vpc.cidr_block }}"
    name: "{{ aws_vars.aws.vpc.name }}"
    tags: "{{ aws_vars.aws.vpc.tags }}"
    tenancy: default
  register: vpc_net