- name: subnet
  ec2_vpc_subnet:
    region: "{{ aws_vars.aws.common.region }}"
    state: present
    vpc_id: "{{ vpc_net.vpc.id }}"
    az: "{{ aws_vars.aws.common.region }}{{ item.value.zone }}"
    cidr: "{{ item.value.cidr }}"
    tags: "{{ item.value.tags }}"
  with_dict: "{{ aws_vars.aws.vpc.subnet }}"
  register: vpc_subnet