- name: subnet
  ec2_vpc_subnet:
    region: "{{ vars.aws.common.region }}"
    state: present
    vpc_id: "{{ vpc_net_fact.vpcs[0].id }}"
    az: "{{ vars.aws.common.region }}{{ item.value.zone }}"
    cidr: "{{ item.value.cidr }}"
    tags: "{{ item.value.tags }}"
  with_dict: "{{ vars.aws.vpc.subnet }}"
  register: vpc_subnet

- debug: var=vpc_subnet